repos:
  # Make sure that Jupyter notebooks under version control
  # have their outputs stripped before committing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: ".ipynb"

  # Run Black - the uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black  # Run Black - the uncompromising Python code formatter
      - id: black-jupyter  # Run Black - the uncompromising Python code formatter (Jupyter version)


  # Add some general purpose useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Make sure that contained YAML files are well-formed
      - id: check-yaml
      # Trim trailing whitespace of all sorts
      - id: trailing-whitespace
      # Sort lines in requirements files
      - id: requirements-txt-fixer
      # Apply a file size limit of 500kB
      - id: check-added-large-files
        exclude: "parzivai/parzival.png"
      # Simple parser validation of e.g. pyproject.toml
      - id: check-toml
      # Unify file endings
      - id: end-of-file-fixer

  - repo: https://github.com/rhysd/actionlint
    rev: "v1.7.4"
    hooks:
      - id: actionlint
