name:
  parzivai
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - streamlit
  - pandas
  - numpy
  - spacy
  - selenium
  - beautifulsoup4
  - requests
  - pip
  - pip:
      - ipykernel
      - build
      - spacy-streamlit
      - langchain-community
      - pydantic
      - sentence-transformers
      - streamlit-feedback
      - webdriver-manager
variables:
  PYTHONPATH: "python"
