name: CI
on:
  push:
    branches:
      - main
      - setup
  pull_request:
    branches:
      - main
      - setup
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    name: Testing on ${{ matrix.os }} with Python ${{ matrix.python }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - "3.9"
          - "3.12"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python package and run tests
      run: |
        python -m pip install -v .
        python -m pip install -r requirements-dev.txt
        cd parzivai
        python -m pytest -svv --cov=. --cov-report=xml
