name: Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: install parzivai
      run: |
        pip install -e .
        python -m pip install -r requirements-dev.txt
    - name: get pandoc
      run: |
        sudo apt-get install -y pandoc
    - name: Build documentation
      run: |
        cd docs
        make html
    - name: Push changes to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs # The folder the action should deploy.
